name: django-cars

services:
  db:
    image: postgres:latest
    container_name: carsdb
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432

  app:
    build: .
    container_name: carsapp
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
